/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root/route'
import { Route as ConnectedRouteRouteImport } from './routes/connected/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as ConnectedSwiftplayRouteRouteImport } from './routes/connected/swiftplay/route'
import { Route as ConnectedLobbyRouteRouteImport } from './routes/connected/lobby/route'
import { Route as ConnectedInvitesRouteRouteImport } from './routes/connected/invites/route'
import { Route as ConnectedCustomRouteRouteImport } from './routes/connected/custom/route'
import { Route as ConnectedCreateLobbyRouteRouteImport } from './routes/connected/create-lobby/route'
import { Route as ConnectedClashRouteRouteImport } from './routes/connected/clash/route'
import { Route as ConnectedChampSelectRouteRouteImport } from './routes/connected/champ-select/route'
import { Route as ConnectedArenaRouteRouteImport } from './routes/connected/arena/route'
import { Route as ConnectedIndexRouteRouteImport } from './routes/connected/index/route'
import { Route as PrototypeLogoIndexRouteImport } from './routes/prototype/logo/index'

const ConnectedRouteRoute = ConnectedRouteRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedSwiftplayRouteRoute = ConnectedSwiftplayRouteRouteImport.update({
  id: '/swiftplay',
  path: '/swiftplay',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedLobbyRouteRoute = ConnectedLobbyRouteRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedInvitesRouteRoute = ConnectedInvitesRouteRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedCustomRouteRoute = ConnectedCustomRouteRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedCreateLobbyRouteRoute =
  ConnectedCreateLobbyRouteRouteImport.update({
    id: '/create-lobby',
    path: '/create-lobby',
    getParentRoute: () => ConnectedRouteRoute,
  } as any)
const ConnectedClashRouteRoute = ConnectedClashRouteRouteImport.update({
  id: '/clash',
  path: '/clash',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedChampSelectRouteRoute =
  ConnectedChampSelectRouteRouteImport.update({
    id: '/champ-select',
    path: '/champ-select',
    getParentRoute: () => ConnectedRouteRoute,
  } as any)
const ConnectedArenaRouteRoute = ConnectedArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedIndexRouteRoute = ConnectedIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const PrototypeLogoIndexRoute = PrototypeLogoIndexRouteImport.update({
  id: '/prototype/logo/',
  path: '/prototype/logo/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/connected': typeof ConnectedRouteRouteWithChildren
  '/connected/': typeof ConnectedIndexRouteRoute
  '/connected/arena': typeof ConnectedArenaRouteRoute
  '/connected/champ-select': typeof ConnectedChampSelectRouteRoute
  '/connected/clash': typeof ConnectedClashRouteRoute
  '/connected/create-lobby': typeof ConnectedCreateLobbyRouteRoute
  '/connected/custom': typeof ConnectedCustomRouteRoute
  '/connected/invites': typeof ConnectedInvitesRouteRoute
  '/connected/lobby': typeof ConnectedLobbyRouteRoute
  '/connected/swiftplay': typeof ConnectedSwiftplayRouteRoute
  '/prototype/logo/': typeof PrototypeLogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/connected': typeof ConnectedIndexRouteRoute
  '/connected/arena': typeof ConnectedArenaRouteRoute
  '/connected/champ-select': typeof ConnectedChampSelectRouteRoute
  '/connected/clash': typeof ConnectedClashRouteRoute
  '/connected/create-lobby': typeof ConnectedCreateLobbyRouteRoute
  '/connected/custom': typeof ConnectedCustomRouteRoute
  '/connected/invites': typeof ConnectedInvitesRouteRoute
  '/connected/lobby': typeof ConnectedLobbyRouteRoute
  '/connected/swiftplay': typeof ConnectedSwiftplayRouteRoute
  '/prototype/logo': typeof PrototypeLogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/connected': typeof ConnectedRouteRouteWithChildren
  '/connected/': typeof ConnectedIndexRouteRoute
  '/connected/arena': typeof ConnectedArenaRouteRoute
  '/connected/champ-select': typeof ConnectedChampSelectRouteRoute
  '/connected/clash': typeof ConnectedClashRouteRoute
  '/connected/create-lobby': typeof ConnectedCreateLobbyRouteRoute
  '/connected/custom': typeof ConnectedCustomRouteRoute
  '/connected/invites': typeof ConnectedInvitesRouteRoute
  '/connected/lobby': typeof ConnectedLobbyRouteRoute
  '/connected/swiftplay': typeof ConnectedSwiftplayRouteRoute
  '/prototype/logo/': typeof PrototypeLogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connected'
    | '/connected/'
    | '/connected/arena'
    | '/connected/champ-select'
    | '/connected/clash'
    | '/connected/create-lobby'
    | '/connected/custom'
    | '/connected/invites'
    | '/connected/lobby'
    | '/connected/swiftplay'
    | '/prototype/logo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connected'
    | '/connected/arena'
    | '/connected/champ-select'
    | '/connected/clash'
    | '/connected/create-lobby'
    | '/connected/custom'
    | '/connected/invites'
    | '/connected/lobby'
    | '/connected/swiftplay'
    | '/prototype/logo'
  id:
    | '__root__'
    | '/'
    | '/connected'
    | '/connected/'
    | '/connected/arena'
    | '/connected/champ-select'
    | '/connected/clash'
    | '/connected/create-lobby'
    | '/connected/custom'
    | '/connected/invites'
    | '/connected/lobby'
    | '/connected/swiftplay'
    | '/prototype/logo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  ConnectedRouteRoute: typeof ConnectedRouteRouteWithChildren
  PrototypeLogoIndexRoute: typeof PrototypeLogoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connected': {
      id: '/connected'
      path: '/connected'
      fullPath: '/connected'
      preLoaderRoute: typeof ConnectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected/swiftplay': {
      id: '/connected/swiftplay'
      path: '/swiftplay'
      fullPath: '/connected/swiftplay'
      preLoaderRoute: typeof ConnectedSwiftplayRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/lobby': {
      id: '/connected/lobby'
      path: '/lobby'
      fullPath: '/connected/lobby'
      preLoaderRoute: typeof ConnectedLobbyRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/invites': {
      id: '/connected/invites'
      path: '/invites'
      fullPath: '/connected/invites'
      preLoaderRoute: typeof ConnectedInvitesRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/custom': {
      id: '/connected/custom'
      path: '/custom'
      fullPath: '/connected/custom'
      preLoaderRoute: typeof ConnectedCustomRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/create-lobby': {
      id: '/connected/create-lobby'
      path: '/create-lobby'
      fullPath: '/connected/create-lobby'
      preLoaderRoute: typeof ConnectedCreateLobbyRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/clash': {
      id: '/connected/clash'
      path: '/clash'
      fullPath: '/connected/clash'
      preLoaderRoute: typeof ConnectedClashRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/champ-select': {
      id: '/connected/champ-select'
      path: '/champ-select'
      fullPath: '/connected/champ-select'
      preLoaderRoute: typeof ConnectedChampSelectRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/arena': {
      id: '/connected/arena'
      path: '/arena'
      fullPath: '/connected/arena'
      preLoaderRoute: typeof ConnectedArenaRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/connected/': {
      id: '/connected/'
      path: ''
      fullPath: '/connected/'
      preLoaderRoute: typeof ConnectedIndexRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/prototype/logo/': {
      id: '/prototype/logo/'
      path: '/prototype/logo'
      fullPath: '/prototype/logo/'
      preLoaderRoute: typeof PrototypeLogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectedRouteRouteChildren {
  ConnectedIndexRouteRoute: typeof ConnectedIndexRouteRoute
  ConnectedArenaRouteRoute: typeof ConnectedArenaRouteRoute
  ConnectedChampSelectRouteRoute: typeof ConnectedChampSelectRouteRoute
  ConnectedClashRouteRoute: typeof ConnectedClashRouteRoute
  ConnectedCreateLobbyRouteRoute: typeof ConnectedCreateLobbyRouteRoute
  ConnectedCustomRouteRoute: typeof ConnectedCustomRouteRoute
  ConnectedInvitesRouteRoute: typeof ConnectedInvitesRouteRoute
  ConnectedLobbyRouteRoute: typeof ConnectedLobbyRouteRoute
  ConnectedSwiftplayRouteRoute: typeof ConnectedSwiftplayRouteRoute
}

const ConnectedRouteRouteChildren: ConnectedRouteRouteChildren = {
  ConnectedIndexRouteRoute: ConnectedIndexRouteRoute,
  ConnectedArenaRouteRoute: ConnectedArenaRouteRoute,
  ConnectedChampSelectRouteRoute: ConnectedChampSelectRouteRoute,
  ConnectedClashRouteRoute: ConnectedClashRouteRoute,
  ConnectedCreateLobbyRouteRoute: ConnectedCreateLobbyRouteRoute,
  ConnectedCustomRouteRoute: ConnectedCustomRouteRoute,
  ConnectedInvitesRouteRoute: ConnectedInvitesRouteRoute,
  ConnectedLobbyRouteRoute: ConnectedLobbyRouteRoute,
  ConnectedSwiftplayRouteRoute: ConnectedSwiftplayRouteRoute,
}

const ConnectedRouteRouteWithChildren = ConnectedRouteRoute._addFileChildren(
  ConnectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  ConnectedRouteRoute: ConnectedRouteRouteWithChildren,
  PrototypeLogoIndexRoute: PrototypeLogoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
