[package]
name = "conduit"
version = "0.1.12"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aes = "0.8"
base64 = "0.22"
cbc = "0.1"
dirs = "6"
futures = "0.3"
native-tls = "0.2"
pem = "3"
pkcs8 = "0.10"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
regex = "1"
rsa = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-autostart = "2"
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
tauri-plugin-process = "2"
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
thiserror = "2"
tokio = { version = "1", features = ["time", "rt", "sync", "macros", "net", "io-util", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "local-time"] }
url = "2"
whoami = "1"

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
irelia = { version = "0.11.1", features = ["rest", "ws"] }

[dev-dependencies]
tokio-test = "0.4"

[features]
custom-protocol = ["tauri/custom-protocol"]
