import { defineConfig } from 'oxlint'

const reactDoctorRules = {
  'react-doctor/no-derived-state-effect': 'warn',
  'react-doctor/no-fetch-in-effect': 'warn',
  'react-doctor/no-mirror-prop-effect': 'warn',
  'react-doctor/no-mutable-in-deps': 'warn',
  'react-doctor/no-cascading-set-state': 'warn',
  'react-doctor/no-effect-chain': 'warn',
  'react-doctor/no-effect-event-handler': 'warn',
  'react-doctor/no-effect-event-in-deps': 'warn',
  'react-doctor/no-event-trigger-state': 'warn',
  'react-doctor/no-prop-callback-in-effect': 'warn',
  'react-doctor/no-derived-useState': 'warn',
  'react-doctor/no-direct-state-mutation': 'warn',
  'react-doctor/no-set-state-in-render': 'warn',
  'react-doctor/prefer-use-effect-event': 'warn',
  'react-doctor/prefer-useReducer': 'warn',
  'react-doctor/prefer-use-sync-external-store': 'warn',
  'react-doctor/rerender-lazy-state-init': 'warn',
  'react-doctor/rerender-functional-setstate': 'warn',
  'react-doctor/rerender-dependencies': 'warn',
  'react-doctor/rerender-state-only-in-handlers': 'warn',
  'react-doctor/rerender-defer-reads-hook': 'warn',
  'react-doctor/advanced-event-handler-refs': 'warn',
  'react-doctor/effect-needs-cleanup': 'warn',
  'react-doctor/no-giant-component': 'warn',
  'react-doctor/no-render-in-render': 'warn',
  'react-doctor/no-many-boolean-props': 'warn',
  'react-doctor/no-react19-deprecated-apis': 'warn',
  'react-doctor/no-render-prop-children': 'warn',
  'react-doctor/no-nested-component-definition': 'warn',
  'react-doctor/react-compiler-destructure-method': 'warn',
  'react-doctor/no-legacy-class-lifecycles': 'warn',
  'react-doctor/no-legacy-context-api': 'warn',
  'react-doctor/no-default-props': 'warn',
  'react-doctor/no-react-dom-deprecated-apis': 'warn',
  'react-doctor/no-usememo-simple-expression': 'warn',
  'react-doctor/no-layout-property-animation': 'warn',
  'react-doctor/rerender-memo-with-default-value': 'warn',
  'react-doctor/rerender-memo-before-early-return': 'warn',
  'react-doctor/rerender-transitions-scroll': 'warn',
  'react-doctor/rerender-derived-state-from-hook': 'warn',
  'react-doctor/async-defer-await': 'warn',
  'react-doctor/async-await-in-loop': 'warn',
  'react-doctor/rendering-animate-svg-wrapper': 'warn',
  'react-doctor/rendering-hoist-jsx': 'warn',
  'react-doctor/rendering-hydration-mismatch-time': 'warn',
  'react-doctor/no-inline-prop-on-memo-component': 'warn',
  'react-doctor/rendering-hydration-no-flicker': 'warn',
  'react-doctor/rendering-script-defer-async': 'warn',
  'react-doctor/rendering-usetransition-loading': 'warn',
  'react-doctor/no-transition-all': 'warn',
  'react-doctor/no-global-css-variable-animation': 'warn',
  'react-doctor/no-large-animated-blur': 'warn',
  'react-doctor/no-scale-from-zero': 'warn',
  'react-doctor/no-permanent-will-change': 'warn',
  'react-doctor/no-eval': 'warn',
  'react-doctor/no-secrets-in-client-code': 'warn',
  'react-doctor/no-generic-handler-names': 'warn',
  'react-doctor/js-flatmap-filter': 'warn',
  'react-doctor/js-combine-iterations': 'warn',
  'react-doctor/js-tosorted-immutable': 'warn',
  'react-doctor/js-hoist-regexp': 'warn',
  'react-doctor/js-hoist-intl': 'warn',
  'react-doctor/js-cache-property-access': 'warn',
  'react-doctor/js-length-check-first': 'warn',
  'react-doctor/js-min-max-loop': 'warn',
  'react-doctor/js-set-map-lookups': 'warn',
  'react-doctor/js-batch-dom-css': 'warn',
  'react-doctor/js-index-maps': 'warn',
  'react-doctor/js-cache-storage': 'warn',
  'react-doctor/js-early-exit': 'warn',
  'react-doctor/no-barrel-import': 'warn',
  'react-doctor/no-dynamic-import-path': 'warn',
  'react-doctor/no-full-lodash-import': 'warn',
  'react-doctor/no-moment': 'warn',
  'react-doctor/prefer-dynamic-import': 'warn',
  'react-doctor/use-lazy-motion': 'warn',
  'react-doctor/no-undeferred-third-party': 'warn',
  'react-doctor/no-array-index-as-key': 'warn',
  'react-doctor/no-polymorphic-children': 'warn',
  'react-doctor/rendering-conditional-render': 'warn',
  'react-doctor/rendering-svg-precision': 'warn',
  'react-doctor/no-prevent-default': 'warn',
  'react-doctor/no-uncontrolled-input': 'warn',
  'react-doctor/no-document-start-view-transition': 'warn',
  'react-doctor/no-flush-sync': 'warn',
  'react-doctor/server-auth-actions': 'warn',
  'react-doctor/server-after-nonblocking': 'warn',
  'react-doctor/server-no-mutable-module-state': 'warn',
  'react-doctor/server-cache-with-object-literal': 'warn',
  'react-doctor/server-hoist-static-io': 'warn',
  'react-doctor/server-dedup-props': 'warn',
  'react-doctor/server-sequential-independent-await': 'warn',
  'react-doctor/server-fetch-without-revalidate': 'warn',
  'react-doctor/client-passive-event-listeners': 'warn',
  'react-doctor/client-localstorage-no-version': 'warn',
  'react-doctor/no-inline-bounce-easing': 'warn',
  'react-doctor/no-z-index-9999': 'warn',
  'react-doctor/no-inline-exhaustive-style': 'warn',
  'react-doctor/no-side-tab-border': 'warn',
  'react-doctor/no-pure-black-background': 'warn',
  'react-doctor/no-gradient-text': 'warn',
  'react-doctor/no-dark-mode-glow': 'warn',
  'react-doctor/no-justified-text': 'warn',
  'react-doctor/no-tiny-text': 'warn',
  'react-doctor/no-wide-letter-spacing': 'warn',
  'react-doctor/no-gray-on-colored-background': 'warn',
  'react-doctor/no-layout-transition-inline': 'warn',
  'react-doctor/no-disabled-zoom': 'warn',
  'react-doctor/no-outline-none': 'warn',
  'react-doctor/no-long-transition-duration': 'warn',
  'react-doctor/design-no-bold-heading': 'warn',
  'react-doctor/design-no-redundant-padding-axes': 'warn',
  'react-doctor/design-no-redundant-size-axes': 'warn',
  'react-doctor/design-no-space-on-flex-children': 'warn',
  'react-doctor/design-no-em-dash-in-jsx-text': 'warn',
  'react-doctor/design-no-three-period-ellipsis': 'warn',
  'react-doctor/design-no-default-tailwind-palette': 'warn',
  'react-doctor/design-no-vague-button-label': 'warn',
  'react-doctor/async-parallel': 'warn',
  'react-doctor/query-stable-query-client': 'warn',
  'react-doctor/query-no-rest-destructuring': 'warn',
  'react-doctor/query-no-void-query-fn': 'warn',
  'react-doctor/query-no-query-in-effect': 'warn',
  'react-doctor/query-mutation-missing-invalidation': 'warn',
  'react-doctor/query-no-usequery-for-mutation': 'warn',
} as const

export default defineConfig({
  plugins: ['typescript', 'import', 'react', 'unicorn'],
  jsPlugins: [
    {
      name: 'tanstack-router',
      specifier: '@tanstack/eslint-plugin-router',
    },
    {
      name: 'react-doctor',
      specifier: 'react-doctor/oxlint-plugin',
    },
  ],
  env: {
    browser: true,
    node: true,
  },
  rules: {
    '@typescript-eslint/no-explicit-any': 'error',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'unicorn/filename-case': [
      'error',
      {
        case: 'kebabCase',
        ignore: ['^__root$', '^vite-env$', '^routeTree\\.gen$'],
      },
    ],
    'tanstack-router/create-route-property-order': 'error',
  },
  overrides: [
    {
      files: ['web/**/*.{ts,tsx}'],
      rules: {
        ...reactDoctorRules,
        'tanstack-router/create-route-property-order': 'error',
      },
    },
    {
      files: ['conduit/**/*.{ts,tsx}'],
      rules: reactDoctorRules,
    },
  ],
  ignorePatterns: [
    '**/node_modules/**',
    '**/dist/**',
    '**/*.d.ts',
    '**/routeTree.gen.ts',
    '**/tsconfig.tsbuildinfo',
    'rift/**',
    'web/**',
  ],
})
