packages:
  - 'loom'
  - 'leyline'
  - 'conduit'
  - 'packages/*'

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

strictPeerDependencies: false
autoInstallPeers: true

allowBuilds:
  msw: true
  msgpackr-extract: false

blockExoticSubdeps: true
trustPolicy: provenance
