import { defineConfig } from 'vite-plus';

import { ALL_REACT_DOCTOR_RULES } from 'oxlint-plugin-react-doctor';

const reactDoctorRules = Object.fromEntries(
  Object.entries(ALL_REACT_DOCTOR_RULES).map(([key, severity]) => {
    if (key.includes('/nextjs-')) return [key, 'off']
    if (key.includes('/tanstack-start-')) return [key, 'off']
    if (key.includes('/rn-')) return [key, 'off']
    if (key.endsWith('/react-in-jsx-scope')) return [key, 'off']
    if (key.endsWith('/rules-of-hooks')) return [key, 'warn']
    return [key, severity]
  })
)

export default defineConfig({
  fmt: {
    printWidth: 128,
    singleQuote: true,
    jsxSingleQuote: true,
    semi: false,
    trailingComma: 'all',
    ignorePatterns: [
      '**/node_modules/**',
      '**/dist/**',
      '**/*.d.ts',
      '**/bun-test.d.ts',
      '**/routeTree.gen.ts',
      '**/tsconfig.tsbuildinfo',
      'leyline/**',
      'loom/tests/**',
      'loom/src/**/*.test.ts',
      'loom/src/testing/**',
    ],
    sortImports: {
      newlinesBetween: true,
      internalPattern: ['@/', '~/', '@shoma/'],
    },
    sortTailwindcss: {
      functions: ['clsx', 'cn', 'cva', 'twMerge'],
      attributes: ['className', 'class'],
    },
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'import'],
    jsPlugins: [
      {
        name: 'tanstack-router',
        specifier: '@tanstack/eslint-plugin-router',
      },
      {
        name: 'react-doctor',
        specifier: 'oxlint-plugin-react-doctor',
      },
    ],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
      browser: true,
      node: true,
    },
    ignorePatterns: [
      '**/node_modules/**',
      '**/dist/**',
      '**/*.d.ts',
      '**/bun-test.d.ts',
      '**/routeTree.gen.ts',
      '**/tsconfig.tsbuildinfo',
      'leyline/**',
      'loom/tests/**',
      'loom/src/**/*.test.ts',
      'loom/src/testing/**',
    ],
    rules: {
      'arrow-body-style': ['error', 'always'],
      'constructor-super': 'error',
      curly: ['error', 'all'],
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nested-ternary': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'never',
        },
      ],
      'typescript/consistent-type-imports': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
      'unicorn/filename-case': [
        'error',
        {
          case: 'kebabCase',
          ignore: ['^__root$', '^vite-env$', '^routeTree\\.gen$'],
        },
      ],
      'tanstack-router/create-route-property-order': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/routeTree.gen.ts', '**/bun-test.d.ts'],
        rules: {
          'arrow-body-style': 'off',
          curly: 'off',
          'no-nested-ternary': 'off',
          'typescript/consistent-type-assertions': 'off',
          'typescript/consistent-type-imports': 'off',
        },
      },
      {
        files: [
          'conduit/**/*.{js,jsx,ts,tsx}',
          'leyline/**/*.{js,jsx,ts,tsx}',
          'loom/**/*.{js,jsx,ts,tsx}',
          'packages/**/*.{js,jsx,ts,tsx}',
        ],
        env: {
          es2026: true,
        },
      },
      {
        files: ['loom/**/*.{ts,tsx}'],
        rules: {
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
          'react/only-export-components': [
            'warn',
            {
              allowConstantExport: true,
            },
          ],
          'tanstack-router/create-route-property-order': 'error',
          ...reactDoctorRules,
        },
      },
      {
        files: ['loom/src/routes/**/*.{ts,tsx}', 'loom/src/components/ui/**/*.{ts,tsx}'],
        rules: {
          'react/only-export-components': 'off',
        },
      },
      {
        files: ['conduit/**/*.{ts,tsx}'],
        rules: reactDoctorRules,
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
});
