export default {
  categories: {
    correctness: 'error',
    style: 'warn',
    suspicious: 'error',
  },
  env: {
    builtin: true,
    node: true,
  },
  globals: {
    Bun: 'readonly',
  },
  plugins: ['eslint', 'import', 'oxc', 'typescript', 'unicorn'],
  jsPlugins: [
    {
      name: 'perfectionist',
      specifier: 'eslint-plugin-perfectionist',
    },
    {
      name: 'style',
      specifier: '@stylistic/eslint-plugin',
    },
    '../tools/oxlint-plugin-custom/index.js',
  ],
  rules: {
    'arrow-body-style': 'warn',
    'constructor-super': 'error',
    'curly': ['error', 'all'],
    'custom-imports/no-duplicate-imports': 'off',
    'eslint/id-length': 'off',
    'eslint/init-declarations': 'off',
    'eslint/max-statements': 'off',
    'eslint/no-magic-numbers': 'off',
    'eslint/no-ternary': 'off',
    'eslint/sort-imports': 'off',
    'for-direction': 'error',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'getter-return': 'error',
    'import/consistent-type-specifier-style': 'off',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-named-export': 'off',
    'import/prefer-default-export': 'off',
    'new-cap': 'off',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'off',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-nested-ternary': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unassigned-vars': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-shadow': 'off',
    'no-underscore-dangle': ['error', { allow: ['_tag', '_op', '_id'] }],
    'no-useless-assignment': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'perfectionist/sort-exports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'perfectionist/sort-imports': [
      'error',
      {
        customGroups: [
          {
            elementNamePattern: ['^react$'],
            groupName: 'react',
            selector: 'type',
          },
          {
            elementNamePattern: ['^react$'],
            groupName: 'react',
            selector: 'import',
          },
        ],
        groups: ['builtin', 'react', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
        internalPattern: [
          '^@/.+',
          '^~/.+',
          '^#.+',
          '^app',
          '^assets',
          '^auth',
          '^components',
          '^config',
          '^constants',
          '^hooks',
          '^icons',
          '^interfaces',
          '^lab',
          '^layout',
          '^locales',
          '^middlewares',
          '^mocks',
          '^pages',
          '^plugins',
          '^providers',
          '^router',
          '^services',
          '^store',
          '^styles',
          '^tests',
          '^theme',
          '^types',
          '^utils',
          '^views',
        ],
        newlinesBetween: 1,
      },
    ],
    'perfectionist/sort-named-exports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'perfectionist/sort-named-imports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'preserve-caught-error': 'error',
    'require-yield': 'error',
    'style/jsx-newline': ['error'],
    'style/max-len': 'off',
    'style/padding-line-between-statements': 'warn',
    'typescript/ban-ts-comment': 'error',
    'typescript/consistent-type-assertions': [
      'error',
      {
        assertionStyle: 'never',
      },
    ],
    'typescript/consistent-type-imports': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
    'unicorn/filename-case': [
      'error',
      {
        case: 'kebabCase',
        ignore: ['^__root$', '^vite-env$', String.raw`^routeTree\.gen$`],
      },
    ],
    'unicorn/no-null': 'off',
    'use-isnan': 'error',
    'valid-typeof': 'error',
  },
  overrides: [
    {
      files: ['**/*.ts', '**/*.mts', '**/*.cts'],
      rules: {
        'constructor-super': 'off',
        'getter-return': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-redeclare': 'off',
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-undef': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-var': 'error',
        'no-with': 'off',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
      },
    },
    {
      files: ['**/bun-test.d.ts'],
      rules: {
        'arrow-body-style': 'off',
        'curly': 'off',
        'no-nested-ternary': 'off',
        'typescript/consistent-type-assertions': 'off',
        'typescript/consistent-type-imports': 'off',
      },
    },
    {
      files: [
        'scripts/**/*',
        '**/tests/**/*',
        '**/*.test.ts',
        '**/*-test.ts',
        'vite.*.ts',
        'vitest.config.*',
      ],
      rules: {
        'import/no-nodejs-modules': 'off',
        'no-useless-assignment': 'off',
        'typescript/consistent-type-assertions': 'off',
      },
    },
    {
      env: {
        es2026: true,
      },
      files: ['leyline/**/*.{js,jsx,ts,tsx}'],
    },
  ],
}
