export const GAMEFLOW_PHASE_NONE = 'None' as const
export const GAMEFLOW_PHASE_LOBBY = 'Lobby' as const
export const GAMEFLOW_PHASE_MATCHMAKING = 'Matchmaking' as const
export const GAMEFLOW_PHASE_READY_CHECK = 'ReadyCheck' as const
export const GAMEFLOW_PHASE_CHAMP_SELECT = 'ChampSelect' as const
export const GAMEFLOW_PHASE_IN_PROGRESS = 'InProgress' as const

export const GAMEFLOW_PHASES = {
  CHAMP_SELECT: GAMEFLOW_PHASE_CHAMP_SELECT,
  IN_PROGRESS: GAMEFLOW_PHASE_IN_PROGRESS,
  LOBBY: GAMEFLOW_PHASE_LOBBY,
  MATCHMAKING: GAMEFLOW_PHASE_MATCHMAKING,
  NONE: GAMEFLOW_PHASE_NONE,
  READY_CHECK: GAMEFLOW_PHASE_READY_CHECK,
} as const

export const GAMEFLOW_PHASE_VALUES = [
  GAMEFLOW_PHASE_NONE,
  GAMEFLOW_PHASE_LOBBY,
  GAMEFLOW_PHASE_MATCHMAKING,
  GAMEFLOW_PHASE_READY_CHECK,
  GAMEFLOW_PHASE_CHAMP_SELECT,
  GAMEFLOW_PHASE_IN_PROGRESS,
] as const

export type GameflowPhase = (typeof GAMEFLOW_PHASE_VALUES)[number]
